version: '2'

volumes:
  orderer.example.com:
  peer0.partyc.example.com:

services:
  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
    - /var/run/:/host/var/run/

  partyc:
    container_name: irs-partyc
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=partyc.peer0
      - CORE_PEER_ADDRESS=irs-partyc:7051
      - CORE_PEER_LISTENADDRESS=irs-partyc:7051
      - CORE_PEER_GOSSIP_ENDPOINT=irs-partyc:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=irs-partyc:7051
      - CORE_PEER_LOCALMSPID=partyc
    volumes:
        - ./crypto-config/peerOrganizations/partyc.example.com/peers/peer0.partyc.example.com/msp:/etc/hyperledger/fabric/msp
        - peer0.partyc.example.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

 
